<?php

declare(strict_types=1);

namespace Cipi\Sdk\Resources;

final class BasicAuth extends Resource
{
    /**
     * @return array<string, mixed>
     */
    public function status(string $app): array
    {
        return $this->client->get($this->appPath($app).'/basicauth');
    }

    /**
     * Password is generated by the panel when omitted, and returned once.
     *
     * @return array<string, mixed>
     */
    public function enable(string $app, ?string $user = null, ?string $password = null): array
    {
        return $this->client->post(
            $this->appPath($app).'/basicauth/enable',
            $this->withoutNulls([
                'user' => $user,
                'password' => $password,
            ]),
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function disable(string $app): array
    {
        return $this->client->post($this->appPath($app).'/basicauth/disable');
    }
}
